<div class='book swiper-wrapper'><div class='page swiper-slide' data-page='1'><p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
<table style='border-collapse:collapse;margin-left:auto;margin-right:auto;'><tbody><tr><td style='width:395.07692307692px;  border-left border-top border-bottom border-right text-align: right; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'><span style='font-weight: bold; font-family: Calibri;'></style>Генеральному директору</span></p> 
</td></tr><tr><td style='width:395.07692307692px;  border-left border-top border-bottom border-right text-align: right; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'><span style='font-weight: bold; font-family: Calibri;'></style>Общества с ограниченной ответственностью &laquo;СИБИНТЕК-СОФТ&raquo;</span></p> 
</td></tr><tr><td style='width:395.07692307692px;  border-left border-top border-bottom border-right text-align: right; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'><span style='font-weight: bold; font-family: Calibri;'></style>(ООО &laquo;СИБИНТЕК-СОФТ&raquo;)</span></p> 
</td></tr><tr><td style='width:395.07692307692px;  border-left border-top border-bottom border-right text-align: right; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'><span style='font-weight: bold; font-family: Calibri;'></style>Российская Федерация, 125284, г. Москва, Беговая ул., д. 3, стр. 1, эт/пом/ком 21/LII/1,2,6-8,12-14</span></p> 
</td></tr><tr><td style='width:395.07692307692px;  border-left border-top border-bottom border-right text-align: right; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
</td></tr><tr><td style='width:395.07692307692px;  border-left border-top border-bottom border-right text-align: right; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style> &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(Фамилия, инициалы)</span></p> 
</td></tr></tbody></table><p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
<p style=' margin-top:0px; margin-bottom: 12px;text-align: center;'><span style='font-weight: bold; font-family: Calibri;'></style>СОГЛАСИЕ</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;text-align: center;'><span style='font-weight: bold; font-family: Calibri;'></style>на обработку персональных данных</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
<table style='border-collapse:collapse;margin-left:auto;margin-right:auto;'><tbody><tr><td style='width:33.615384615385px;  border-left border-top border-bottom border-right text-align: left; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'>  <span style=' font-family: Calibri;'>Я,</span></p> 
</td><td colspan='7'; style='width:683.46153846154px;  border-left:0px none #; border-top:0px none #; border-bottom:1px solid #000000; border-right:0px none #; text-align: left; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
</td><td style='width:21.846153846154px;  border-left border-top border-bottom border-right text-align: left; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'>  <span style=' font-family: Calibri;'>,</span></p> 
</td></tr><tr><td style='width:33.615384615385px;  border-left border-top border-bottom border-right text-align: center; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
</td><td colspan='8'; style='width:705.30769230769px;  border-left border-top border-bottom border-right text-align: center; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;text-align: center;'><span style=' font-family: Calibri;'></style>(Фамилия, Имя, Отчество)</span></p> 
</td></tr><tr><td colspan='5'; style='width:305px;  border-left border-top border-bottom border-right text-align: left; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>зарегистрированная (ый) по адресу:</span></p> 
</td><td colspan='4'; style='width:433.92307692308px;  border-left:0px none #; border-top:0px none #; border-bottom:1px solid #000000; border-right:0px none #; text-align: left; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
</td></tr><tr><td colspan='9'; style='width:738.92307692308px;  border-left:0px none #; border-top:0px none #; border-bottom:1px solid #000000; border-right:0px none #; text-align: left; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
</td></tr><tr><td colspan='9'; style='width:738.92307692308px;  border-left:0px none #; border-top:0px none #; border-bottom:1px solid #000000; border-right:0px none #; text-align: left; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
</td></tr><tr><td colspan='2'; style='width:130.53846153846px;  border-left:0px none #; border-top:1px solid #000000; border-bottom:0px none #; border-right:0px none #; text-align: left; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>паспорт серия</span></p> 
</td><td style='width:65.461538461538px;  border-left:0px none #; border-top:1px solid #000000; border-bottom:1px solid #000000; border-right:0px none #; text-align: left; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
</td><td style='width:34.846153846154px;  border-left:0px none #; border-top:1px solid #000000; border-bottom:0px none #; border-right:0px none #; text-align: left; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>№</span></p> 
</td><td colspan='2'; style='width:106.92307692308px;  border-left:0px none #; border-top:1px solid #000000; border-bottom:1px solid #000000; border-right:0px none #; text-align: left; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
</td><td style='width:76.307692307692px;  border-left:0px none #; border-top:1px solid #000000; border-bottom:0px none #; border-right:0px none #; text-align: left; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>, выдан </span></p> 
</td><td colspan='2'; style='width:324.84615384615px;  border-left:0px none #; border-top:1px solid #000000; border-bottom:1px solid #000000; border-right:0px none #; text-align: left; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
</td></tr><tr><td colspan='8'; style='width:717.07692307692px;  border-left:0px none #; border-top:0px none #; border-bottom:1px solid #000000; border-right:0px none #; text-align: left; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
</td><td style='width:21.846153846154px;  border-left border-top border-bottom border-right text-align: left; vertical-align: top;background-color: #FFFFFF; color: #auto;'><p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>,</span></p> 
</td></tr></tbody></table><p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>_____________________________________________________________________________</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;text-align: center;'><span style=' font-family: Calibri;'></style>(номер телефона)</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
<p style=' margin-top:0px; margin-bottom: 12px;'>  <span style=' font-family: Calibri;'> (далее Субъект), даю согласие ООО &laquo;СИБИНТЕК-СОФТ&raquo; (Общество с ограниченной ответственностью &laquo;СИБИНТЕК-СОФТ&raquo;), находящемуся по адресу: Российская Федерация, 125284, г. </div><div class="page swiper-slide" data-page="2">Москва, Беговая ул., д. 3, стр. 1, эт/пом/ком 21/LII/1,2,6-8,12-14,&nbsp;(далее - Оператор), осуществлять любое действие (операцию) или совокупность действий (операций), совершаемых с использованием средств автоматизации или без использования таких средств моими персональными данными, включая сбор, запись, систематизацию, накопление, хранение, уточнение (обновление, изменение), извлечение, использование, передачу (распространение, предоставление, доступ), обезличивание, блокирование, удаление, уничтожение моих нижеперечисленных персональных данных в течение всего периода действия моего трудового договора с Оператором, а также после расторжения трудового договора с учётом сроков хранения документов в соответствии с архивным законодательством Российской Федерации:</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
<table style='border-collapse:collapse;margin-left:auto;margin-right:auto;'><tbody><tr><td style='width:599.53846153846px;  border-left:1px solid #000000; border-top:1px solid #000000; border-bottom:1px solid #000000; border-right:1px solid #000000; text-align: left; vertical-align: center;'><p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>Перечень и цель</span></p> 
</td><td style='width:119.69230769231px;  border-left:1px solid #000000; border-top:1px solid #000000; border-bottom:1px solid #000000; border-right:1px solid #000000; text-align: left; vertical-align: top;'><p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>Подпись субъекта персональных данных</span></p> 
</td></tr><tr><td style='width:599.53846153846px;  border-left:1px solid #000000; border-top:1px solid #000000; border-bottom:1px solid #000000; border-right:1px solid #000000; text-align: left; vertical-align: top;'><p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>Фамилия, имя, отчество, дата и место рождения, гражданство;&nbsp;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>прежние фамилия, имя, отчество,&nbsp;дата, место и причина изменения (в&nbsp;случае изменения); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>документ, удостоверяющий личность (серия, номер, кем и когда выдан); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style></div><div class="page swiper-slide" data-page="3">паспорт, удостоверяющий личность гражданина&nbsp;Российской&nbsp;Федерации&nbsp;за&nbsp;пределами&nbsp;Российской&nbsp;Федерации&nbsp;(серия,&nbsp;номер,&nbsp;кем&nbsp;и&nbsp;когда&nbsp;выдан); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>документы, подтверждающие личность иностранного гражданина или лица без гражданства, право на пребывание (проживание) в Российской Федерации; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>трудовая деятельность (включая работу по совместительству, предпринимательскую деятельность и т.п.); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>сведения о налоговом статусе (резидент/нерезидент);</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>идентификационный номер налогоплательщика;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>номер страхового свидетельства обязательного пенсионного страхования; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>адрес и дата регистрации по месту жительства (месту пребывания); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>адрес фактического проживания; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>номер контактного телефона или сведения о других способах связи, в том числе адрес электронной почты;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>фотографическое изображение; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>информация о степени владения иностранными языками и языками народов Российской Федерации;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>образование (названия образовательных учреждений, период обучения/переподготовки/повышения квалификации, данные документа, направление подготовки или специальность, квалификация, профессия); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>ученая степень, ученое звание и степень (дата присвоения, данные документа);</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>сведения о полученных удостоверениях или свидетельствах, а также дипломов о прохождении специальных видов обучения/аттестации или проверки знаний, в том числе для получения допуска к выполнению отдельных видов работ; данные о прохождении военной службы; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>отношение к воинской обязанности, сведения по воинскому учету (для граждан, пребывающих в запасе, и лиц, подлежащих призыву на военную службу);</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>государственные награды, иные награды и знаки отличия (дата награждения, кем награжден);</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>степень родства, фамилии, имена, отчества, даты рождения, гражданство, место работы, должность, адрес места жительства близких родственников и членов семьи (близкие родственники и члены семьи &ndash; это лица, состоящие в близком родстве или свойстве с должностным лицом/работником: родители (в т.ч. усыновители), дети (в т.ч. усыновленные), полнородные и неполнородные братья (в т.ч. двоюродные), сестры (в т.ч. двоюродные), бабушки, дедушки, внуки, супруги, а также родители (в т.ч. усыновители), дети (в т.ч. усыновленные), братья (в т.ч. двоюродные), сестры (в т.ч. двоюродные), бабушки, дедушки и внуки супругов, супруги детей, дети (в т.ч. усыновленные) и супруги полнородных и неполнородных братьев и сестер);</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>пребывание за границей (страна периоды и цель пребывания);</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>близкие родственники, постоянно проживающие за границей и (или) оформляющие документы для выезда на постоянное место жительства в другое государство (фамилия, имя, отчество, период проживания за границей);</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>о планируемых и/или совершенных операциях с финансовыми инструментами Оператора (ценные бумаги, в т.ч. акции, или производный финансовый инструмент, цена которого зависит от ценных бумаг Оператора);</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>допуск к государственной тайне, оформленный за период работы, службы, учебы (форма, номер и дата); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>результаты обязательных медицинских осмотров (обследований), медицинских заключений о признании полностью неспособным/ограниченно способным к трудовой </div><div class="page swiper-slide" data-page="4">деятельности, выданных в порядке, установленном федеральными законами и иными нормативными правовыми актами Российской Федерации;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>иные персональные данные, необходимые для достижения иных целей, возникающих в период трудовых отношений с Оператором,</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style='font-weight: bold; font-style: italic; font-family: Calibri;'></style>предоставляю Оператору для обработки в целях обеспечения соблюдения в отношении меня законодательства Российской Федерации в сфере трудовых и непосредственно связанных с ними отношений, в том числе связанных с противодействием коррупции и корпоративному мошенничеству.</span></p> 
</td><td style='width:119.69230769231px;  border-left:1px solid #000000; border-top:1px solid #000000; border-bottom:1px solid #000000; border-right:1px solid #000000; text-align: left; vertical-align: top;'><p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
</td></tr><tr><td style='width:599.53846153846px;  border-left:1px solid #000000; border-top:1px solid #000000; border-bottom:1px solid #000000; border-right:1px solid #000000; text-align: left; vertical-align: top;'><p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style></div><div class="page swiper-slide" data-page="5">Фамилия, имя, отчество, дата и место рождения;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>документ, удостоверяющий личность (серия, номер, кем и когда выдан); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>трудовая деятельность (включая работу по совместительству, предпринимательскую деятельность и т.п.); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>сведения о налоговом статусе (резидент/нерезидент); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>идентификационный номер налогоплательщика; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>номер страхового свидетельства обязательного пенсионного страхования</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>адрес и дата регистрации по месту жительства (месту пребывания), </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>адрес фактического проживания; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>номер контактного телефона или сведения о других способах связи, в том числе адрес электронной почты; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>фотографическое изображение;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>образование (названия образовательных учреждений, период обучения/переподготовки/повышения квалификации, данные документа, направление подготовки или специальность, квалификация, профессия);</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>ученая степень, ученое звание и степень (дата присвоения, данные документа); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>сведения о полученных удостоверениях или свидетельствах, а также дипломов о прохождении специальных видов обучения/аттестации или проверки знаний, в том числе для получения допуска к выполнению отдельных видов работ; данные о прохождении военной службы; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>отношение к воинской обязанности, сведения по воинскому учету (для граждан, пребывающих в запасе, и лиц, подлежащих призыву на военную службу);</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>государственные награды, иные награды и знаки отличия (дата награждения, кем награжден);</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>степень родства, фамилии, имена, отчества, даты рождения, гражданство, место работы, должность, адрес места жительства близких родственников и членов семьи (близкие родственники и члены семьи &ndash; это лица, состоящие в близком родстве или свойстве с должностным лицом/работником: родители (в т.ч. усыновители), дети (в т.ч. усыновленные), полнородные и неполнородные братья (в т.ч. двоюродные), сестры (в т.ч. двоюродные), бабушки, дедушки, внуки, супруги, а также родители (в т.ч. усыновители), дети (в т.ч. усыновленные), братья (в т.ч. двоюродные), сестры (в т.ч. двоюродные), бабушки, дедушки и внуки супругов, супруги детей, дети (в т.ч. усыновленные) и супруги полнородных и неполнородных братьев и сестер); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>результаты оценки уровня развития профессиональных знаний и навыков работника; информация по зачислению в кадровый резерв; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>иные персональные данные, необходимые для достижения иных целей, возникающих в период трудовых отношений с Оператором,</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style='font-weight: bold; font-style: italic; font-family: Calibri;'></style>предоставляю Оператору для передачи в ООО&nbsp;ИК&nbsp;&laquo;СИБИНТЕК&raquo; (Общество с ограниченной ответственностью &quot;Сибирская Интернет Компания&quot;, юридический адрес: 117152, Москва г, Загородное ш., дом № 1, корпус 1), ПАО&nbsp;&laquo;НК Роснефть&raquo; </div><div class="page swiper-slide" data-page="6">(Публичное акционерное общество &laquo;Нефтяная компания &laquo;Роснефть&raquo;, юридический адрес: 115035, город Москва, Софийская набережная, 26/1), для проведения корпоративных кадровых мероприятий в период трудовых отношений с Оператором.</span></p> 
</td><td style='width:119.69230769231px;  border-left:1px solid #000000; border-top:1px solid #000000; border-bottom:1px solid #000000; border-right:1px solid #000000; text-align: left; vertical-align: top;'><p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
</td></tr><tr><td style='width:599.53846153846px;  border-left:1px solid #000000; border-top:1px solid #000000; border-bottom:1px solid #000000; border-right:1px solid #000000; text-align: left; vertical-align: top;'><p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>Фамилия, имя, отчество; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>должность с указанием структурного подразделения; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>табельный номер;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>номер служебного телефона (стационарного и мобильного);</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>размещение рабочего места;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>адрес служебной электронной почты; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>sip-адрес (для систем обмена мгновенными сообщениями);</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>наименование Оператора;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>логин в информационных системах ПАО &laquo;НК &laquo;Роснефть&raquo;;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>сведения о наличии работника на рабочем месте; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>фотографическое изображение;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>иные персональные данные, необходимые для достижения заявленной цели, обработка которых может потребоваться в период трудовых отношений с Оператором,</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style='font-weight: bold; font-style: italic; font-family: Calibri;'></style>предоставляю Оператору для размещения в общедоступных источниках справочных данных Оператора, а также для передачи в</span><span style=' font-family: Calibri;'>&nbsp;</span><span style='font-weight: bold; font-style: italic; font-family: Calibri;'>ПАО &laquo;НК &laquo;Роснефть&raquo;,&nbsp;ООО&nbsp;ИК&nbsp;&laquo;СИБИНТЕК&raquo;, ООО &laquo;АйЭмТи&raquo;&nbsp;(Общество с ограниченной ответственностью&nbsp;&laquo;АйЭмТи&raquo;, юридический адрес: 124460, город Москва, город Зеленоград, 4803-й проезд, дом 27 строение 1) для размещения в общедоступных источниках справочных данных.&nbsp;</span></p> 
</td><td style='width:119.69230769231px;  border-left:1px solid #000000; border-top:1px solid #000000; border-bottom:1px solid #000000; border-right:1px solid #000000; text-align: left; vertical-align: top;'><p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
</td></tr><tr><td style='width:599.53846153846px;  border-left:1px solid #000000; border-top:1px solid #000000; border-bottom:1px solid #000000; border-right:1px solid #000000; text-align: left; vertical-align: top;'><p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>Фамилия, имя, отчество, дата и место рождения, гражданство;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>прежние фамилия, имя, отчество, дата, место и причина изменения (в случае изменения); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>документ, удостоверяющий личность (серия, номер, кем и когда выдан); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>паспорт, удостоверяющий личность гражданина Российской Федерации за пределами Российской Федерации (серия, номер, кем и когда выдан); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>документы, подтверждающие личность иностранного гражданина или лица без гражданства, право на пребывание (проживание) в Российской Федерации; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>трудовая деятельность (включая работу по совместительству, предпринимательскую деятельность и т.п.); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>сведения о налоговом статусе (резидент/нерезидент);</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>идентификационный номер налогоплательщика;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>номер страхового свидетельства обязательного пенсионного страхования;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>адрес и дата регистрации по месту жительства (месту пребывания);</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>адрес фактического проживания; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>номер контактного телефона или сведения о других способах связи, в том числе адрес электронной почты;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>фотографическое изображение; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>информация о степени владения иностранными языками и языкам народов Российской Федерации;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>образование (названия образовательных учреждений, период обучения/переподготовки/повышения квалификации, данные документа, направление подготовки или специальность, квалификация, профессия); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>ученая степень, ученое звание и степень (дата присвоения, данные документа); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>сведения о полученных удостоверениях или свидетельствах, а также дипломов о прохождении специальных видов обучения/аттестации или проверки знаний, в том числе </div><div class="page swiper-slide" data-page="7">для получения допуска к выполнению отдельных видов работ; данные о прохождении военной службы; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>отношение к воинской обязанности, сведения по воинскому учету (для граждан, пребывающих в запасе, и лиц, подлежащих призыву на военную службу);</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>государственные награды, иные награды и знаки отличия (дата награждения, кем награжден); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>степень родства, фамилии, имена, отчества, даты рождения, гражданство, место работы, должность, адрес места жительства близких родственников и членов семьи (близкие родственники и члены семьи &ndash; это лица, состоящие в близком родстве или свойстве с должностным лицом/работником: родители (в т.ч. усыновители), дети (в т.ч. усыновленные), полнородные и неполнородные братья (в т.ч. двоюродные), сестры (в т.ч. двоюродные), бабушки, дедушки, внуки, супруги, а также родители (в т.ч. усыновители), дети (в т.ч. усыновленные), братья (в т.ч. двоюродные), сестры (в т.ч. двоюродные), бабушки, дедушки и внуки супругов, супруги детей, дети (в т.ч. усыновленные) и супруги полнородных и неполнородных братьев и сестер); &nbsp;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>пребывание за границей (страна периоды и цель пребывания); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>близкие родственники, постоянно проживающие за границей и (или) оформляющие документы для выезда на постоянное место жительства в другое государство (фамилия, имя, отчество, период проживания за границей); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>о планируемых и/или совершенных операциях с финансовыми инструментами Оператора (ценные бумаги, в т.ч. акции, или производный финансовый инструмент, цена которого зависит от ценных бумаг Оператора); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>допуск к государственной тайне, оформленный за период работы, службы, учебы (форма, номер и дата); </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>результаты обязательных медицинских осмотров (обследований), медицинских заключений о признании полностью неспособным/ограниченно способным к трудовой деятельности, выданных в порядке, установленном федеральными законами и иными нормативными правовыми актами Российской Федерации;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>иные персональные данные, необходимые для достижения иных целей, возникающих в период трудовых отношений с Оператором,</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style>&nbsp;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style='font-weight: bold; font-style: italic; font-family: Calibri;'></style>предоставляю Оператору для передачи в ООО &laquo;РН-Учет&raquo; (Общество с ограниченной ответственностью &laquo;РН-Учет&raquo;, юридический адрес: 125284, г. Москва, ул. Беговая, д.3, строение 1) для ведения бухгалтерского и налогового учета, составления отчетности в соответствии с требованиями законодательства Российской Федерации о бухгалтерском учете, Налогового кодекса Российской Федерации , иных нормативных актов, учетной политики и прочих локальных нормативных документов Заказчика, на основании первичных учетных документов, отражающих факты хозяйственной жизни экономического субъекта, в соответствии с Договором оказания услуг по ведению бухгалтерского и налогового учета и для оказания комплекса учетных услуг в соответствии с Договором оказания комплекса учетных услуг и договором на оказание услуг кадрового администрирования.</span></p> 
</td><td style='width:119.69230769231px;  border-left:1px solid #000000; border-top:1px solid #000000; border-bottom:1px solid #000000; border-right:1px solid #000000; text-align: left; vertical-align: top;'><p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
</td></tr></tbody></table><p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
<p style=' margin-top:0px; margin-bottom: 12px;text-indent: 65px;'><span style=' font-family: Calibri;'></style></div><div class="page swiper-slide" data-page="8">Передача моих персональных данных иным лицам, не указанным в настоящем Согласии, может осуществляться только с моего письменного согласия, за исключением случае, предусмотренных законодательством Российской Федерации.</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;text-indent: 55px;'><span style=' font-family: Calibri;'></style>Я ознакомлен(а), что:</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;text-indent: 55px;'><span style=' font-family: Calibri;'></style>1)&nbsp;согласие на обработку персональных данных действует с даты подписания настоящего Согласия в течение всего срока действия трудового договора, заключенного между Оператором и мною; </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;text-indent: 55px;'><span style=' font-family: Calibri;'></style>2)&nbsp;согласие на обработку персональных данных может быть отозвано мною на основании письменного заявления в установленной форме;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;text-indent: 55px;'><span style=' font-family: Calibri;'></style>3)&nbsp;в случае отзыва согласия на обработку персональных данных Оператор вправе продолжить обработку персональных данных без Согласия при наличии оснований, указанных в пунктах 2-11 части 1 статьи 6, части 2 статьи 10 и части 2 статьи 11 Федерального закона от 27.07.2006 № 152-ФЗ &laquo;О персональных данных&raquo;;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;text-indent: 55px;'><span style=' font-family: Calibri;'></style></div><div class="page swiper-slide" data-page="9">4)&nbsp;после прекращения трудовых отношений с Оператором (моего увольнения) персональные данные хранятся в течение срока хранения документов, предусмотренных действующим законодательством Российской Федерации;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;text-indent: 55px;'><span style=' font-family: Calibri;'></style>5)&nbsp;персональные данные, предоставляемые в отношении третьих лиц, будут обрабатываться только в целях осуществления и выполнения Оператором полномочий и обязанностей, возложенных на него законодательством по противодействию коррупции. </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;text-indent: 55px;'><span style=' font-family: Calibri;'></style>Подтверждаю, что ознакомлен(а) с положениями Федерального закона от 27.07.2006 № 152-ФЗ &laquo;О персональных данных&raquo; и &nbsp;Политикой Компании&nbsp; &laquo;В области обработки персональных данных&nbsp; № П2-03 П-07, размещённой на сайте <a href='https://www.rosneft.ru/' target='_blank' rel='noopener noreferrer'>https://www.rosneft.ru/</a>.</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;text-indent: 55px;'><span style=' font-family: Calibri;'></style>Права и обязанности в области защиты персональных данных мне разъяснены.</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
<p style=' margin-top:0px; margin-bottom: 12px;'>  <span style=' font-family: Calibri;'>Дата начала обработки персональных данных: </span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style></div><div class="page swiper-slide" data-page="10"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_______________________________________</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(число, месяц, год)</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_________________________________</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'><span style=' font-family: Calibri;'></style> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(подпись)</span></p> 
<p style=' margin-top:0px; margin-bottom: 12px;'>&nbsp;</p> 
<br>&nbsp;</div></div>